apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: graphql
  name: graphql
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    app: graphql
  type: LoadBalancer
status:
  loadBalancer: {}
