apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jwt
  name: jwt
spec:
  ports:
  - name: "4080"
    port: 4080
    targetPort: 4080
  selector:
    app: jwt
  type: LoadBalancer
status:
  loadBalancer: {}