apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-external-port
    protocol: TCP
  - port: 19092
    name: kafka-internal-port
    protocol: TCP
  selector:
    app: kafka
  type: LoadBalancer