kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://kafka-service:19092,OUTSIDE://127.0.0.1:9092"
        - name: KAFKA_LISTENERS
          value: "INSIDE://:19092,OUTSIDE://:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181"
        image: wurstmeister/kafka
        name: kafka
        ports:
        - containerPort: 9092
      hostname: kafka
      restartPolicy: Always