apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: central-library
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: rootpw
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo:4.0.4
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-files
        - mountPath: /docker-entrypoint-initdb.d
          name: db-init
      restartPolicy: Always
      volumes:
        - name: db-init
          hostPath:
            path: /path/to/project/advanced-graphql-server-tutorial/data-sources/mongodb/init
            type: Directory
        - name: db-files
          hostPath:
            path: /path/to/project/advanced-graphql-server-tutorial/data-sources/mongodb/db
            type: Directory
status: {}

