apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: central-library
        - name: MYSQL_PASSWORD
          value: graphqlpw
        - name: MYSQL_ROOT_PASSWORD
          value: rootpw
        - name: MYSQL_USER
          value: graphql
        image: mysql:8.0.13
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-files
        - mountPath: /docker-entrypoint-initdb.d
          name: db-init
      restartPolicy: Always
      volumes:
        - name: db-init
          hostPath:
            path: /path/to/project/advanced-graphql-server-tutorial/data-sources/mysql/init
            type: Directory
        - name: db-files
          hostPath:
            path: /path/to/project/advanced-graphql-server-tutorial/data-sources/mysql/db
            type: Directory
status: {}